image = "build/minimum.img"
boot_rom = "../bootloader/bootloader.bin"
max_ticks = 500000

[[ram_prefill]]
address = 0x40030000
length = 131072
value = 165

[assert]
ticks_at_least = 500000
execution_lifecycle = "paused"
shutdown_lifecycle = "stopped"
mmu_enabled = true
trace_values = [0x20000001]
